from django.shortcuts import render
from mysite.forms import mailForm
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail
from django.contrib.auth.decorators import user_passes_test
from mysite.models import eMail
# Create your views here.

def index(request):
    form = modal_check(request)
    if form is True:
        return HttpResponseRedirect('/site/')
    return render(request, 'mysite/index.html',{'form':form})

def portfolio(request):
    form = modal_check(request)
    if form is True:
        return HttpResponseRedirect('/')
    return render(request, 'mysite/portfolio.html',{'form':form})

def portfolio_details(request, name):
    portfolio = ["logo", "banners"]
    if name in portfolio:
        pass
    else:
        name=""

    return render(request,'mysite/portfolio_'+name, {} )

def about(request):
    form = modal_check(request)
    if form is True:
        return HttpResponseRedirect('/')
    return render(request, 'mysite/about.html',{'form':form})

def policy(request):
    form = modal_check(request)
    if form is True:
        return HttpResponseRedirect('/')
    return render(request, 'mysite/policy.html',{'form':form})

def faq(request):
    if request.method == 'POST':
        if "message" in request.POST:
            email = request.POST["email"]
            message = request.POST["message"]
#            host_name= request.META['REMOTE_HOST']
            ip  =request.META['REMOTE_ADDR']
            browser =request.META['HTTP_USER_AGENT']
            
            message_body  = "E-mail from: "+ email+ "\n"+ message + "\n" + "IP: "+ip+ "\n"+ "Browser and client info: " + browser
            print(message_body)
            send_mail('Development Test', message_body, 'mfaiq1996@gmail.com',['m_faiq@live.co.uk'], fail_silently=False)
            print("Sent")

    form= modal_check(request)

    if form is True:
        return HttpResponseRedirect('/')
    return render(request, 'mysite/faq.html', {'form': form})

def modal_check(request):
    if request.method == 'POST':
        form = mailForm(request.POST)
        if form.is_valid():
            ip  =request.META['REMOTE_ADDR']
            browser =request.META['HTTP_USER_AGENT']
            email = form.cleaned_data['email']
            mail = eMail.objects.get_or_create(email = email)
            mail.name = form.cleaned_data['name']
            mail.details = "IP: "+ip+ "\n"+ "Browser and client info: " + browser
            mail.time = datetime.now()
            mail.save()
            send_mail('Greetings', 'Autogenerated E-mail sent by M. Faiq. Your app is working fine.', 'mfaiq1996@gmail.com', [email], fail_silently=False)
            return True;
    
    form = mailForm()
    return form


@user_passes_test(lambda u: u.is_superuser)
def emails(request):
    emails = eMail.objects.all().order_by('time')
    
    return render(request, 'mysite/emails.html', {'emails': emails})
