from django.shortcuts import render
from mysite.forms import mailForm
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail
# Create your views here.

def index(request):
    form = modal_check(request)
    if form is True:
        return HttpResponseRedirect('/site/')
    return render(request, 'mysite/index.html',{'form':form})

def portfolio(request):
    form = modal_check(request)
    if form is True:
        return HttpResponseRedirect('/site/')
    return render(request, 'mysite/portfolio.html',{'form':form})

def about(request):
    form = modal_check(request)
    if form is True:
        return HttpResponseRedirect('/site/')
    return render(request, 'mysite/about.html',{'form':form})

def policy(request):
    form = modal_check(request)
    if form is True:
        return HttpResponseRedirect('/site/')
    return render(request, 'mysite/policy.html',{'form':form})


def faq(request):
    if request.method == 'POST':
        if "message" in request.POST:
            email = request.POST["email"]
            message = request.POST["message"]
            host_name= request.META['REMOTE_HOST']
            ip  =request.META['REMOTE_ADDR']
            browser =request.META['HTTP_USER_AGENT']
            
            message_body  = "E-mail from: "+ email+ "\n"+ message + "\n" + host_name + "\n" + "IP: "+ip+ "\n"+ "Browser and client info: " + browser
            print(message_body)
            send_mail('Development Test', message_body, 'mfaiq1996@gmail.com',['m_faiq@live.co.uk'], fail_silently=False)
            print("Sent")

    form= modal_check(request)

    if form is True:
        return HttpResponseRedirect('/site/')
    return render(request, 'mysite/faq.html', {'form': form})

def modal_check(request):
    if request.method == 'POST':
        form = mailForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            print email
            send_mail('Development Test', 'Autogenerated E-mail sent by M. Faiq. Your app is working fine.', 'mfaiq1996@gmail.com',
    [email], fail_silently=False)
            print "Sent"
            form.save()
            return True;
        else:
            error = "<ul class=\"errorlist\"><li>E mail with this Email already exists.</li></ul>"
            if error == str(form.errors['email']):
                
                email = form.data['email']
                print email
                send_mail('Development Test', 'Autogenerated E-mail sent by M. Faiq. Your app is working fine.', 'mfaiq1996@gmail.com',[email], fail_silently=False)
                print "Sent"
                return True;
            
    
    form = mailForm()
    return form
